site_name: LectureBot for ἐντελέχεια.άι
site_url: 'https://lecture-bot.entelecheia.ai/'
site_description: 'ChatGPT answers your questions about the content of the page you are currently viewing.'
site_author: Young Joon Lee <entelecheia@hotmail.com>
docs_dir: docs/
repo_name: entelecheia/entelecheia-lecture-bot
repo_url: 'https://github.com/entelecheia/entelecheia-lecture-bot'
edit_uri: edit/main/docs/

plugins:
  - search
  - mkdocs-video
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  favicon: https://assets.entelecheia.ai/favicon.png
  logo: https://assets.entelecheia.ai/favicon.png
  palette:
    scheme: slate
  features:
    - navigation.expand
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - navigation.indexes

extra:
  analytics:
    provider: google
    property: G-PE36E23XVM
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
