site_name: LectureBot for ἐντελέχεια.αι
site_url: 'https://chat.entelecheia.ai/'
site_description: 'ChatGPT answers your questions about the content of the page you are currently viewing.'
site_author: entelecheia
docs_dir: docs/
repo_name: entelecheia/entelecheia-lecture-bot
repo_url: 'https://github.com/entelecheia/entelecheia-lecture-bot'
nav:
  - Home: index.md
theme:
  name: material
  palette:
    scheme: slate
