---
name: Release

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Semantic release
        id: semantic_release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload release assets
        if: steps.semantic_release.outputs.new_release_version != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.semantic_release.outputs.upload_url }}
          asset_path: ./dist/chrome.zip
          asset_name: entelecheia-ai-chrome-${{ steps.semantic_release.outputs.new_release_version }}.zip
          asset_content_type: application/zip
